# This file was generated by GoReleaser. DO NOT EDIT.
class Everest < Formula
  desc "some description"
  homepage "https://github.com/mpppk/everest"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mpppk/everest/releases/download/v0.1.0/everest_0.1.0_darwin_amd64.tar.gz"
    sha256 "3eaf83cc7626c6b8b1e4248cdbaa60b3c00f38e25f12e01906f7d45a2eedd1ed"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mpppk/everest/releases/download/v0.1.0/everest_0.1.0_linux_amd64.tar.gz"
      sha256 "db9a9938d67e3cb19375dac11c310dafe245a962a29185c243f9c38328f2114e"
    end
  end

  def install
    bin.install "everest"
  end

  test do
    system "#{bin}/hlb --help"
  end
end
