# This file was generated by GoReleaser. DO NOT EDIT.
class Everest < Formula
  desc "some description"
  homepage "https://github.com/mpppk/everest"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mpppk/everest/releases/download/v0.1.0/everest_0.1.0_darwin_amd64.tar.gz"
    sha256 "b5d69f725be81b501ecfe5176c691a74d381848108f09a52ae4e071d8f467dd9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mpppk/everest/releases/download/v0.1.0/everest_0.1.0_linux_amd64.tar.gz"
      sha256 "a478db2fb7da83485e6b9532178c71b7cdb9b6f6cecc18a1817a557ea6519731"
    end
  end

  def install
    bin.install "everest"
  end

  test do
    system "#{bin}/hlb --help"
  end
end
