# This file was generated by GoReleaser. DO NOT EDIT.
class Everest < Formula
  desc "some description"
  homepage "https://github.com/mpppk/everest"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mpppk/everest/releases/download/v0.1.0/everest_0.1.0_darwin_amd64.tar.gz"
    sha256 "5fdc786ad063c55adc922db10193b1e8a82117c34766af920dcfaf34ddecd54e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mpppk/everest/releases/download/v0.1.0/everest_0.1.0_linux_amd64.tar.gz"
      sha256 "7420304b3eb8ccf44d299ec160ab168c47391051ccf449e07eeb97b6bf580043"
    end
  end

  def install
    bin.install "everest"
  end

  test do
    system "#{bin}/hlb --help"
  end
end
