# This file was generated by GoReleaser. DO NOT EDIT.
class Iroha < Formula
  desc "some description"
  homepage "https://github.com/mpppk/iroha"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mpppk/iroha/releases/download/v0.1.1/iroha_0.1.1_darwin_amd64.tar.gz"
    sha256 "cd6b96ebdaffcfbddaa3b770a3568d30abdb2f9adf00b174afb3fba306abefcd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mpppk/iroha/releases/download/v0.1.1/iroha_0.1.1_linux_amd64.tar.gz"
      sha256 "3288dbdb713074645bc7a5926f4afbd71244e19c8717e18f331dcf7aabafca0b"
    end
  end

  def install
    bin.install "iroha"
  end

  test do
    system "#{bin}/hlb --help"
  end
end
