# This file was generated by GoReleaser. DO NOT EDIT.
class Twitter < Formula
  desc "some description"
  homepage "https://github.com/mpppk/twitter"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mpppk/twitter/releases/download/v0.1.1/twitter_0.1.1_darwin_amd64.tar.gz"
    sha256 "045d0e73fa7ff75c4b059c8577288100c257e3ad3cb68c9d765d96e55151e098"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mpppk/twitter/releases/download/v0.1.1/twitter_0.1.1_linux_amd64.tar.gz"
      sha256 "b6e1bf2885cd118c3d7a47ff58d757d643f254936613927027608bf6bb1dc02a"
    end
  end

  def install
    bin.install "twitter"
  end

  test do
    system "#{bin}/hlb --help"
  end
end
