# This file was generated by GoReleaser. DO NOT EDIT.
class Twitter < Formula
  desc "some description"
  homepage "https://github.com/mpppk/twitter"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mpppk/twitter/releases/download/v0.1.0/twitter_0.1.0_darwin_amd64.tar.gz"
    sha256 "1f4a1a96671dd1451da21d193ae500d66fceed2cd395109285ff9f2f8e7a4983"
  elsif OS.linux?
    url "https://github.com/mpppk/twitter/releases/download/v0.1.0/twitter_0.1.0_linux_amd64.tar.gz"
    sha256 "1de978bc3d8ad4f7bdb824c3c52ba5dc3e3f4b7d77d132202c0b6abd3f5a9251"
  end

  def install
    bin.install "twitter"
  end

  test do
    system "#{bin}/hlb --help"
  end
end
